# Generated by Django 3.2 on 2021-05-16 20:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Programming'), (2, 'Food'), (3, 'Beauty'), (4, 'Plants')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Programming'), (2, 'Food'), (3, 'Beauty'), (4, 'Plants')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_adult',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
